# Generated by Django 5.0.2 on 2024-02-16 20:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('wallet_address', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.wallet')),
            ],
        ),
    ]
