# Generated by Django 5.0.2 on 2024-02-16 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('AWAITING_FULFILLMENT', 'Awaiting Fulfillment'), ('AWAITING_SHIPMENT', 'Awaiting Shipment'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DECLINED', 'Declined'), ('REFUNDED', 'Refunded')], default='PENDING'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('EVENT', 'Event')], default='PENDING'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.user'),
        ),
    ]
