# Generated by Django 5.0.2 on 2024-02-16 22:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_status_order_type_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
