# Generated by Django 5.0.2 on 2024-02-16 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='order_id',
        ),
    ]
