# Generated by Django 5.0.2 on 2024-02-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Authority',
            field=models.CharField(default='dsafdaf', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='event_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('PURCHASE', 'Purchase')]),
        ),
    ]
