# Generated by Django 5.0.2 on 2024-02-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order_authority_alter_order_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('WALLET', 'Wallet'), ('BANK', 'Bank')], default='BANK'),
            preserve_default=False,
        ),
    ]
