# Generated by Django 5.0.2 on 2024-02-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_transaction_response_code_alter_transaction_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Authority',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='event_id',
            field=models.CharField(blank=True, default=213, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ref_id',
            field=models.CharField(blank=True, default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='response_code',
            field=models.IntegerField(blank=True),
        ),
    ]
