# Generated by Django 5.0.2 on 2024-02-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_order_authority_alter_order_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='response_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
